--Implement AFTER Triggers for Automatic Execution After Data Operations.

-- EMPLOYEE_LOG (LOGID, EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE) 

--From the table EMPLOYEE perform the following queries:  

--Part – A: 

--1. Create trigger for printing message after employee record insertion. 
	CREATE OR ALTER TRIGGER emp_insert_trigger
	ON EMPLOYEE
	INSTEAD OF  INSERT
	as
	BEGIN
			PRINT('Employee record inserted successfully.');
	END;

	SELECT * FROM EMPLOYEE
	INSERT INTO EMPLOYEE VALUES(114,'UTTAM','KOTHARI','CSE','35000','RAJKOT','MALE',2026);
	
	DROP TRIGGER emp_insert_trigger

--2. Create trigger for printing message after employee record update. 
	CREATE OR ALTER TRIGGER emp_update_trigger
	ON EMPLOYEE
	AFTER UPDATE
	as
	BEGIN
			PRINT('Employee record updated successfully.');
	END;

	SELECT * FROM EMPLOYEE
	UPDATE EMPLOYEE SET EID = 111
	WHERE FIRSTNAME = 'MAYANK'
	

--3. Create trigger for printing message after employee record deletion.
	CREATE OR ALTER TRIGGER EMP_AFTER_DELETE
	ON EMPLOYEE
	AFTER DELETE
	as
	BEGIN
			PRINT('Employee record deleted successfully.');
	END;

	SELECT * FROM EMPLOYEE

	DELETE FROM  EMPLOYEE 
	WHERE EID = 112

--4. Create trigger for printing message after employee salary increment. 
	CREATE OR ALTER TRIGGER EMP_INCREMENT_SALARY
	ON EMPLOYEE
	AFTER UPDATE
	as
	BEGIN
			DECLARE @NEWSALARY INT
			DECLARE @OLDSALARY INT

			SELECT @NEWSALARY = SALARY FROM inserted
			SELECT @OLDSALARY = SALARY FROM deleted
			
			IF @NEWSALARY > @OLDSALARY
				PRINT('Employee SALARY INCREMENT');

			ELSE 
				PRINT ('EMPLOYEE SALARY DECRESE')
	END;

	SELECT * FROM EMPLOYEE

	UPDATE EMPLOYEE SET SALARY=16000
	WHERE EID = 111

--5. Create trigger for automatically converting CITY names into uppercase during insertion. 
	CREATE OR ALTER TRIGGER emp_city_trigger
	ON EMPLOYEE
	AFTER INSERT
	as
	BEGIN
			DECLARE @CITY VARCHAR(50)
			DECLARE @EID INT
			SELECT @CITY = CITY FROM INSERTED
			SELECT @EID = EID FROM INSERTED

			UPDATE EMPLOYEE 
			SET CITY = UPPER(@CITY)
			WHERE EID = @EID
			
	END;

	SELECT * FROM EMPLOYEE
	INSERT INTO EMPLOYEE VALUES(113,'UTTAM','KOTHARI','CSE','35000','RajKOT','MALE',2026);

--Part – B: 

--6. Create trigger for updating employee city and printing old city and new city name.
	CREATE OR ALTER TRIGGER EMP_CITY_INSERT
	ON EMPLOYEE
	AFTER UPDATE
	as
	BEGIN
			DECLARE @NEWCITY VARCHAR(50)
			DECLARE @OLDCITY VARCHAR(50)

			SELECT @NEWCITY = CITY FROM inserted
			SELECT @OLDCITY = CITY FROM deleted
			
			PRINT ('NEWCITY :'+@NEWCITY + '  '+'OLDCITY :'+ + @OLDCITY)
	END;	
	SELECT * FROM EMPLOYEE

	UPDATE EMPLOYEE SET CITY = 'RAJKOT'
	WHERE EID= 113
	
--7. Create trigger for automatically setting CITY as 'RAJKOT' if no city value is entered during employee 
--insertion. 
	CREATE OR ALTER TRIGGER EMP_CITY_DEFAULT
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
		UPDATE EMPLOYEE
		SET CITY = 'RAJKOT'
		WHERE EID IN (SELECT EID FROM INSERTED)
		AND (CITY IS NULL OR CITY = '');
	END;

	INSERT INTO EMPLOYEE
	VALUES(115,'RAHUL','PATEL','CSE','30000',NULL,'MALE',2026);

	SELECT * FROM EMPLOYEE

--8. Create trigger for automatically adding current year in JOININGYEAR if no value is entered. 
	CREATE OR ALTER TRIGGER EMP_JOININGYEAR_DEFAULT
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
		UPDATE EMPLOYEE
		SET JOININGYEAR = YEAR(GETDATE())
		WHERE EID IN (SELECT EID FROM INSERTED)
		AND JOININGYEAR IS NULL;
	END;

	INSERT INTO EMPLOYEE
	VALUES(116,'RAHUL','SHAH','CSE','32000','RAJKOT','MALE',NULL);

	SELECT * FROM EMPLOYEE

--9. Create trigger for printing employee full name after new employee insertion. 
	CREATE OR ALTER TRIGGER EMP_FULLNAME_INSERT
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
		DECLARE @FIRSTNAME VARCHAR(50)
		DECLARE @LASTNAME VARCHAR(50)

		SELECT @FIRSTNAME = FIRSTNAME FROM INSERTED
		SELECT @LASTNAME = LASTNAME FROM INSERTED

		PRINT('EMPLOYEE FULL NAME : ' + @FIRSTNAME + ' ' + @LASTNAME)
	END;

	SELECT * FROM EMPLOYEE

	INSERT INTO EMPLOYEE
	VALUES(117,'AMIT','PATEL','CSE','35000','RAJKOT','MALE',2026);

--10. Create trigger for automatically assigning department as ‘GENERAL’ if DEPARTMENT value is NULL. 
	CREATE OR ALTER TRIGGER EMP_DEPARTMENT_DEFAULT
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
		UPDATE EMPLOYEE
		SET DEPARTMENT = 'GENERAL'
		WHERE EID IN (SELECT EID FROM INSERTED)
		AND DEPARTMENT IS NULL;
	END;

	SELECT * FROM EMPLOYEE

	INSERT INTO EMPLOYEE
	VALUES(118,'KARAN','SHAH',NULL,'30000','RAJKOT','MALE',2026);

	SELECT * FROM EMPLOYEE
 
--Part – C: 

--11. Create trigger for storing updated employee details such as EID, old salary, new salary, old department, 
--new department, and update date into EMPLOYEE_UPDATE_LOG table. 
	CREATE TABLE EMPLOYEE_UPDATE_LOG
	(
		LOGID INT IDENTITY(1,1),
		EID INT,
		OLDSALARY INT,
		NEWSALARY INT,
		OLDDEPARTMENT VARCHAR(50),
		NEWDEPARTMENT VARCHAR(50),
		UPDATEDATE DATETIME
	);


	CREATE OR ALTER TRIGGER EMPLOYEE_UPDATE_LOG_TRIGGER
	ON EMPLOYEE
	AFTER UPDATE
	AS
	BEGIN
		INSERT INTO EMPLOYEE_UPDATE_LOG
		(EID, OLDSALARY, NEWSALARY, OLDDEPARTMENT, NEWDEPARTMENT, UPDATEDATE)
		SELECT
			D.EID,
			D.SALARY,
			I.SALARY,
			D.DEPARTMENT,
			I.DEPARTMENT,
			GETDATE()
		FROM DELETED D
		INNER JOIN INSERTED I
		ON D.EID = I.EID;
	END;

	SELECT * FROM EMPLOYEE

	UPDATE EMPLOYEE
	SET SALARY = 40000,
		DEPARTMENT = 'CSE'
	WHERE EID = 114;

	SELECT * FROM EMPLOYEE_UPDATE_LOG

--12. Create trigger for storing newly inserted employee details with insertion date into 
--EMPLOYEE_INSERT_LOG table. 
	CREATE TABLE EMPLOYEE_INSERT_LOG
	(
		LOGID INT IDENTITY(1,1),
		EID INT,
		FIRSTNAME VARCHAR(50),
		LASTNAME VARCHAR(50),
		DEPARTMENT VARCHAR(50),
		SALARY INT,
		CITY VARCHAR(50),
		GENDER VARCHAR(20),
		JOININGYEAR INT,
		INSERTDATE DATETIME
	);

	CREATE OR ALTER TRIGGER EMPLOYEE_INSERT_LOG_TRIGGER
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
		INSERT INTO EMPLOYEE_INSERT_LOG
		(EID, FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, CITY, GENDER, JOININGYEAR, INSERTDATE)
		SELECT
			EID,
			FIRSTNAME,
			LASTNAME,
			DEPARTMENT,
			SALARY,
			CITY,
			GENDER,
			JOININGYEAR,
			GETDATE()
		FROM INSERTED;
	END;

	SELECT * FROM EMPLOYEE

	INSERT INTO EMPLOYEE
	VALUES(119,'ROHAN','PATEL','CSE','35000','RAJKOT','MALE',2026);

	SELECT * FROM EMPLOYEE_INSERT_LOG

--13. Create trigger for storing old and new FIRSTNAME values after employee name update into 
--NAME_CHANGE_LOG table. 
	CREATE TABLE NAME_CHANGE_LOG
	(
		LOGID INT IDENTITY(1,1),
		EID INT,
		OLDFIRSTNAME VARCHAR(50),
		NEWFIRSTNAME VARCHAR(50),
		CHANGEDATE DATETIME
	);

	CREATE OR ALTER TRIGGER EMPLOYEE_NAME_CHANGE
	ON EMPLOYEE
	AFTER UPDATE
	AS
	BEGIN
		INSERT INTO NAME_CHANGE_LOG
		(EID, OLDFIRSTNAME, NEWFIRSTNAME, CHANGEDATE)
		SELECT
			D.EID,
			D.FIRSTNAME,
			I.FIRSTNAME,
			GETDATE()
		FROM DELETED D
		INNER JOIN INSERTED I
		ON D.EID = I.EID
		WHERE D.FIRSTNAME <> I.FIRSTNAME;
	END;

	SELECT * FROM EMPLOYEE

	UPDATE EMPLOYEE
	SET FIRSTNAME = 'UTTAM'
	WHERE EID = 114;

	SELECT * FROM NAME_CHANGE_LOG

--14. Create trigger for storing old city and new city details into CITY_UPDATE_LOG table after city update. 
	CREATE TABLE CITY_UPDATE_LOG
	(
		LOGID INT IDENTITY(1,1),
		EID INT,
		OLDCITY VARCHAR(50),
		NEWCITY VARCHAR(50),
		CHANGEDATE DATETIME
	);

	CREATE OR ALTER TRIGGER EMPLOYEE_CITY_CHANGE
	ON EMPLOYEE
	AFTER UPDATE
	AS
	BEGIN
		INSERT INTO CITY_UPDATE_LOG
		(EID, OLDCITY, NEWCITY, CHANGEDATE)
		SELECT
			D.EID,
			D.CITY,
			I.CITY,
			GETDATE()
		FROM DELETED D
		INNER JOIN INSERTED I
		ON D.EID = I.EID
		WHERE D.CITY <> I.CITY;
	END;

	SELECT * FROM EMPLOYEE

	UPDATE EMPLOYEE
	SET CITY = 'AHMEDABAD'
	WHERE EID = 114;

	SELECT * FROM CITY_UPDATE_LOG

--15. Implement INSTEAD OF INSERT trigger on EMPLOYEE table to automatically remove extra spaces from 
--FIRSTNAME and LASTNAME before insertion.
	CREATE OR ALTER TRIGGER EMPLOYEE_SPACE_REMOVE
	ON EMPLOYEE
	INSTEAD OF INSERT
	AS
	BEGIN
		INSERT INTO EMPLOYEE
		(EID, FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, CITY, GENDER, JOININGYEAR)
		SELECT
			EID,
			LTRIM(RTRIM(FIRSTNAME)),
			LTRIM(RTRIM(LASTNAME)),
			DEPARTMENT,
			SALARY,
			CITY,
			GENDER,
			JOININGYEAR
		FROM INSERTED;
	END;

	SELECT * FROM EMPLOYEE

	INSERT INTO EMPLOYEE
	VALUES(120,'   UTTAM   ','   KOTHARI   ','CSE','35000','RAJKOT','MALE',2026);

	SELECT * FROM EMPLOYEE