--From the table EMPLOYEE perform the following queries:  
--Part – A: 
--1. Create a cursor Employee_Cursor to fetch all rows from EMPLOYEE table and display them.

DECLARE @EID INT,@FNAME VARCHAR(50)

DECLARE EMP_CURSOR CURSOR FOR
SELECT EID,FIRSTNAME
FROM EMPLOYEE

OPEN EMP_CURSOR

FETCH NEXT FROM EMP_CURSOR INTO @EID,@FNAME

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT CAST(@EID AS VARCHAR)+' '+@FNAME

    FETCH NEXT FROM EMP_CURSOR INTO @EID,@FNAME
END

CLOSE EMP_CURSOR
DEALLOCATE EMP_CURSOR


--2. Create a cursor to display all female employees from EMPLOYEE table. 
DECLARE @NAME VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME
FROM EMPLOYEE
WHERE GENDER='FEMALE'

OPEN C1

FETCH NEXT FROM C1 INTO @NAME

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @NAME

    FETCH NEXT FROM C1 INTO @NAME
END

CLOSE C1
DEALLOCATE C1

--3. Create a cursor Employee_Cursor_Fetch to fetch records in form of EID_FirstName_LastName. 
--(Example: 101_Hetvi_Patel)
DECLARE @EID INT,@FN VARCHAR(50),@LN VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT EID,FIRSTNAME,LASTNAME
FROM EMPLOYEE

OPEN C1

FETCH NEXT FROM C1 INTO @EID,@FN,@LN

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT CAST(@EID AS VARCHAR)+'_'+@FN+'_'+@LN

    FETCH NEXT FROM C1 INTO @EID,@FN,@LN
END

CLOSE C1
DEALLOCATE C1



--4. Create a cursor to find and display all employees with Salary greater than 12000.
DECLARE @NAME VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME
FROM EMPLOYEE
WHERE SALARY>12000

OPEN C1

FETCH NEXT FROM C1 INTO @NAME

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @NAME

    FETCH NEXT FROM C1 INTO @NAME
END

CLOSE C1
DEALLOCATE C1



--5. Create a cursor to display all employees who joined in year 2022 or later.
DECLARE @NAME VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME
FROM EMPLOYEE
WHERE JOININGYEAR>=2022

OPEN C1

FETCH NEXT FROM C1 INTO @NAME

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @NAME

    FETCH NEXT FROM C1 INTO @NAME
END

CLOSE C1
DEALLOCATE C1



--6. Create a cursor to fetch Employee Name with Department Name. 
--(Example: Raj Mehta works in IT Department) 
DECLARE @NAME VARCHAR(50),@DEPT VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME,DEPARTMENT
FROM EMPLOYEE

OPEN C1

FETCH NEXT FROM C1 INTO @NAME,@DEPT

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @NAME+' works in '+@DEPT+' Department'

    FETCH NEXT FROM C1 INTO @NAME,@DEPT
END

CLOSE C1
DEALLOCATE C1



--7. Create a cursor to update CITY as ‘AHMEDABAD’ for employees whose CITY value is NULL.
DECLARE @EID INT

DECLARE C1 CURSOR FOR
SELECT EID
FROM EMPLOYEE
WHERE CITY IS NULL

OPEN C1

FETCH NEXT FROM C1 INTO @EID

WHILE @@FETCH_STATUS=0
BEGIN
    UPDATE EMPLOYEE
    SET CITY='AHMEDABAD'
    WHERE EID=@EID

    FETCH NEXT FROM C1 INTO @EID
END

CLOSE C1
DEALLOCATE C1


--8. Create a cursor to display Employee Name with City Name. 
--(Example: Deep Patel lives in Rajkot) 
DECLARE @NAME VARCHAR(50),@LN VARCHAR(50),@CITY VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME,LASTNAME,CITY
FROM EMPLOYEE

OPEN C1

FETCH NEXT FROM C1 INTO @NAME,@LN,@CITY

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @NAME+ @LN+' lives in '+ISNULL(@CITY,'NO CITY')

    FETCH NEXT FROM C1 INTO @NAME,@LN,@CITY
END

CLOSE C1
DEALLOCATE C1



--9. Create a cursor to delete employees whose Salary is less than 5000. 
DECLARE @EID INT

DECLARE C1 CURSOR FOR
SELECT EID
FROM EMPLOYEE
WHERE SALARY<5000

OPEN C1

FETCH NEXT FROM C1 INTO @EID

WHILE @@FETCH_STATUS=0
BEGIN
    DELETE FROM EMPLOYEE
    WHERE EID=@EID

    FETCH NEXT FROM C1 INTO @EID
END

CLOSE C1
DEALLOCATE C1


--10. Create a cursor to display employees department-wise.
DECLARE @NAME VARCHAR(50),@DEPT VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME,DEPARTMENT
FROM EMPLOYEE
ORDER BY DEPARTMENT

OPEN C1

FETCH NEXT FROM C1 INTO @NAME,@DEPT

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @DEPT+' - '+@NAME

    FETCH NEXT FROM C1 INTO @NAME,@DEPT
END

CLOSE C1
DEALLOCATE C1



 
--Part – B: 
--11. Create a cursor to count total employees from each department.
DECLARE @DEPT VARCHAR(50), @CNT INT

DECLARE C1 CURSOR FOR
SELECT DEPARTMENT, COUNT(*)
FROM EMPLOYEE
GROUP BY DEPARTMENT

OPEN C1

FETCH NEXT FROM C1 INTO @DEPT,@CNT

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @DEPT+' = '+CAST(@CNT AS VARCHAR)

    FETCH NEXT FROM C1 INTO @DEPT,@CNT
END

CLOSE C1
DEALLOCATE C1


--12. Create a cursor to display employees whose CITY starts with letter ‘R’.
DECLARE @NAME VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME
FROM EMPLOYEE
WHERE CITY LIKE 'R%'

OPEN C1

FETCH NEXT FROM C1 INTO @NAME

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @NAME

    FETCH NEXT FROM C1 INTO @NAME
END

CLOSE C1
DEALLOCATE C1


--13. Create a cursor to display top 3 highest salary employees from EMPLOYEE table. 
DECLARE @NAME VARCHAR(50), @SALARY INT

DECLARE C1 CURSOR FOR
SELECT TOP 3 FIRSTNAME,SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC

OPEN C1

FETCH NEXT FROM C1 INTO @NAME,@SALARY

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @NAME+' '+CAST(@SALARY AS VARCHAR)

    FETCH NEXT FROM C1 INTO @NAME,@SALARY
END

CLOSE C1
DEALLOCATE C1


--14. Create a cursor to calculate total salary department-wise. 
--(Example: IT Department total salary = 33000) 
DECLARE @DEPT VARCHAR(50), @TOTAL INT

DECLARE C1 CURSOR FOR
SELECT DEPARTMENT,SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPARTMENT

OPEN C1

FETCH NEXT FROM C1 INTO @DEPT,@TOTAL

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @DEPT+' Department Total Salary = '+CAST(@TOTAL AS VARCHAR)

    FETCH NEXT FROM C1 INTO @DEPT,@TOTAL
END

CLOSE C1
DEALLOCATE C1



--15. Create a cursor to calculate average salary city-wise.

DECLARE @CITY VARCHAR(50), @AVG_SAL DECIMAL(10,2)

DECLARE C1 CURSOR FOR
SELECT CITY,AVG(SALARY)
FROM EMPLOYEE
GROUP BY CITY

OPEN C1

FETCH NEXT FROM C1 INTO @CITY,@AVG_SAL

WHILE @@FETCH_STATUS=0
BEGIN
    PRINT @CITY+' Average Salary = '+CAST(@AVG_SAL AS VARCHAR)

    FETCH NEXT FROM C1 INTO @CITY,@AVG_SAL
END

CLOSE C1
DEALLOCATE C1

--Part – C: 
--16. Create a cursor to display employee experience using JOININGYEAR. 
--(Example: Raj Mehta has experience = 4 years)
DECLARE @NAME VARCHAR(50),
        @YEAR INT

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME, JOININGYEAR
FROM EMPLOYEE

OPEN C1

FETCH NEXT FROM C1 INTO @NAME,@YEAR

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @NAME + ' has experience = ' +
          CAST(YEAR(GETDATE())-@YEAR AS VARCHAR) +
          ' years'

    FETCH NEXT FROM C1 INTO @NAME,@YEAR
END

CLOSE C1
DEALLOCATE C1


--17. Create a cursor to display employee full name with annual salary. 
--(Example: Hetvi Patel annual salary = 144000) 
DECLARE @FN VARCHAR(50),
        @LN VARCHAR(50),
        @SALARY INT

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME,LASTNAME,SALARY
FROM EMPLOYEE

OPEN C1

FETCH NEXT FROM C1 INTO @FN,@LN,@SALARY

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @FN+' '+@LN+ ' annual salary = '+CAST(@SALARY*12 AS VARCHAR)

    FETCH NEXT FROM C1 INTO @FN,@LN,@SALARY
END

CLOSE C1
DEALLOCATE C1



--18. Create a cursor to calculate total male and female employees separately.
DECLARE @GENDER VARCHAR(10),
        @CNT INT

DECLARE C1 CURSOR FOR
SELECT GENDER,COUNT(*)
FROM EMPLOYEE
GROUP BY GENDER

OPEN C1

FETCH NEXT FROM C1 INTO @GENDER,@CNT

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @GENDER+' = '+CAST(@CNT AS VARCHAR)

    FETCH NEXT FROM C1 INTO @GENDER,@CNT
END

CLOSE C1
DEALLOCATE C1



--19. Create a cursor to display employees whose salary is greater than department average salary.
DECLARE @NAME VARCHAR(50)

DECLARE C1 CURSOR FOR
SELECT FIRSTNAME
FROM EMPLOYEE E
WHERE SALARY >
(SELECT AVG(SALARY)
    FROM EMPLOYEE
    WHERE DEPARTMENT = E.DEPARTMENT)

OPEN C1

FETCH NEXT FROM C1 INTO @NAME

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @NAME

    FETCH NEXT FROM C1 INTO @NAME
END

CLOSE C1
DEALLOCATE C1


--20. Create a cursor to transfer all employees from ADMIN department to HR department. 
DECLARE @EID INT

DECLARE C1 CURSOR FOR
SELECT EID
FROM EMPLOYEE
WHERE DEPARTMENT='ADMIN'

OPEN C1

FETCH NEXT FROM C1 INTO @EID

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE EMPLOYEE
    SET DEPARTMENT='HR'
    WHERE EID=@EID

    FETCH NEXT FROM C1 INTO @EID
END

CLOSE C1
DEALLOCATE C1


